# Generated by Django 4.1.1 on 2022-09-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_logo_options_logo_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=600)),
                ('phone', models.CharField(max_length=600)),
                ('message', models.TextField()),
                ('ip', models.CharField(max_length=300)),
            ],
        ),
    ]
