# Generated by Django 4.1.1 on 2022-09-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Aloqa Bo`limi', 'verbose_name_plural': 'Aloqa Bo`limi'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Sayt Logotipi', 'verbose_name_plural': 'Sayt Logotipi'},
        ),
        migrations.AddField(
            model_name='contact',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='create_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
